### Bir geliştiricinin açık kaynak yazılımlara katkıda bulunup bulunmadığının (```OpenSourcer```) tahminlenmesi
* "```Never```" ve "```Less than once per year```" yanıtları "```Katkıda bulunuyor```", "```Less than once a month but more than once per year```" ve "```Once a month or more often```" yanıtları  "```Katkıda bulunmuyor```" şeklinde ele alınmalıdır.

In [2]:
import pandas as pd
import numpy as np
erol_df=pd.read_csv("survey_results_public.csv")

In [3]:
erol_df.head()

Respondent                                         MainBranch Hobbyist  \
0           1             I am a student who is learning to code      Yes   
1           2             I am a student who is learning to code       No   
2           3  I am not primarily a developer, but I write co...      Yes   
3           4                     I am a developer by profession       No   
4           5                     I am a developer by profession      Yes   

                  OpenSourcer  \
0                       Never   
1     Less than once per year   
2                       Never   
3                       Never   
4  Once a month or more often   

                                          OpenSource  \
0  The quality of OSS and closed source software ...   
1  The quality of OSS and closed source software ...   
2  The quality of OSS and closed source software ...   
3  The quality of OSS and closed source software ...   
4  OSS is, on average, of HIGHER quality than pro...   

                               Employment                 Country  \
0  Not employed, and not looking for work          United Kingdom   
1      Not employed, but looking for work  Bosnia and Herzegovina   
2                      Employed full-time                Thailand   
3                      Employed full-time           United States   
4                      Employed full-time                 Ukraine   

          Student                                            EdLevel  \
0              No                          Primary/elementary school   
1  Yes, full-time  Secondary school (e.g. American high school, G...   
2              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
3              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
4              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      UndergradMajor  ...  \
0                                                NaN  ...   
1                                                NaN  ...   
2                      Web development or web design  ...   
3  Computer science, computer engineering, or sof...  ...   
4  Computer science, computer engineering, or sof...  ...   

                             WelcomeChange  \
0  Just as welcome now as I felt last year   
1  Just as welcome now as I felt last year   
2  Just as welcome now as I felt last year   
3  Just as welcome now as I felt last year   
4  Just as welcome now as I felt last year   

                                        SONewContent   Age Gender Trans  \
0  Tech articles written by other developers;Indu...  14.0    Man    No   
1  Tech articles written by other developers;Indu...  19.0    Man    No   
2  Tech meetups or events in your area;Courses on...  28.0    Man    No   
3  Tech articles written by other developers;Indu...  22.0    Man    No   
4  Tech meetups or events in your area;Courses on...  30.0    Man    No   

                 Sexuality                                 Ethnicity  \
0  Straight / Heterosexual                                       NaN   
1  Straight / Heterosexual                                       NaN   
2  Straight / Heterosexual                                       NaN   
3  Straight / Heterosexual              White or of European descent   
4  Straight / Heterosexual  White or of European descent;Multiracial   

  Dependents           SurveyLength                  SurveyEase  
0         No  Appropriate in length  Neither easy nor difficult  
1         No  Appropriate in length  Neither easy nor difficult  
2        Yes  Appropriate in length  Neither easy nor difficult  
3         No  Appropriate in length                        Easy  
4         No  Appropriate in length                        Easy  

[5 rows x 85 columns]

In [4]:
#Öznitelikleri belirledim ve S1df adlı DateFrame 'e aktardım.'
S1df=erol_df[erol_df.OpenSource.notnull()& erol_df.OpSys.notnull()]
S1df=S1df[["OpenSourcer",'OpenSource','OpSys']]
S1df['OpenSourcer'].replace({"Never":"Katkıda bulunmuyor","Less than once per year":"Katkıda bulunmuyor","Less than once a month but more than once per year":"Katkıda bulunuyor","Once a month or more often":"Katkıda bulunuyor"},inplace=True)
S1df.isnull().sum()

OpenSourcer    0
OpenSource     0
OpSys          0
dtype: int64

In [5]:
S1df

OpenSourcer                                         OpenSource  \
0      Katkıda bulunmuyor  The quality of OSS and closed source software ...   
1      Katkıda bulunmuyor  The quality of OSS and closed source software ...   
2      Katkıda bulunmuyor  The quality of OSS and closed source software ...   
3      Katkıda bulunmuyor  The quality of OSS and closed source software ...   
4       Katkıda bulunuyor  OSS is, on average, of HIGHER quality than pro...   
...                   ...                                                ...   
88875   Katkıda bulunuyor  OSS is, on average, of HIGHER quality than pro...   
88876  Katkıda bulunmuyor  OSS is, on average, of HIGHER quality than pro...   
88877   Katkıda bulunuyor  The quality of OSS and closed source software ...   
88878   Katkıda bulunuyor  The quality of OSS and closed source software ...   
88882  Katkıda bulunmuyor  OSS is, on average, of HIGHER quality than pro...   

             OpSys  
0          Windows  
1          Windows  
2      Linux-based  
3          Windows  
4      Linux-based  
...            ...  
88875      Windows  
88876        MacOS  
88877  Linux-based  
88878      Windows  
88882  Linux-based  

[85923 rows x 3 columns]

In [6]:
#Sutun işlemleri.
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
X=onehotencoder.fit_transform(S1df.drop("OpenSourcer",axis=1)).toarray()
y=S1df["OpenSourcer"]

In [7]:
X

array([[0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [8]:
#5'e 1 oranında verilerimizi 100 random state oalrak ayırıyoruz.
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=100)

In [9]:
#Kullanacağımız metotu belirleyerek import ediyoruz.
from sklearn.linear_model import LogisticRegression
lg_model=LogisticRegression(C=0.1,max_iter=1000)

In [10]:
#Modeli eğitiyoruz.
lg_model.fit(X_train,y_train)

LogisticRegression(C=0.1, max_iter=1000)

In [11]:
#Skorumuzu firek kütüphane üzerinden gösteriyoruz birazdan aşşağıdaki kullanacağımız metotta fark ne kadar olacak merak ettim.
print('Score X_test,y_test: %s- Score X_train,y_train: %s' % (lg_model.score(X_test,y_test),lg_model.score(X_train,y_train)))

Score X_test,y_test: 0.6420133837649112- Score X_train,y_train: 0.6405045244260816


In [12]:
#Tahmin değerlerini sayısal olarak görüyoruz.
from sklearn.metrics import confusion_matrix
tahmin=lg_model.predict(X_test)
confusion_matrix(y_test,tahmin)
#11028 tane true pozitif
#5 tane true negatif

#6 false negatif (6 değer negatifken pozitif bulunmuş)
#6146 false pozitif pozitif 6146 değer negatif bulunmuş

array([[11028,     6],
       [ 6146,     5]], dtype=int64)

In [13]:
S1df.head()

OpenSourcer                                         OpenSource  \
0  Katkıda bulunmuyor  The quality of OSS and closed source software ...   
1  Katkıda bulunmuyor  The quality of OSS and closed source software ...   
2  Katkıda bulunmuyor  The quality of OSS and closed source software ...   
3  Katkıda bulunmuyor  The quality of OSS and closed source software ...   
4   Katkıda bulunuyor  OSS is, on average, of HIGHER quality than pro...   

         OpSys  
0      Windows  
1      Windows  
2  Linux-based  
3      Windows  
4  Linux-based

In [14]:
lg_model.coef_

array([[ 0.2530719 , -0.16135478, -0.09155619,  0.3513407 ,  0.16885741,
         0.01079018, -0.53082735]])

In [15]:
#K değerini 5 vererek CrossVal Score 0.64 Çıkmaktadır.
#Cross Validation Score yukarıdaki yaptığımız normal değerlerlendirme ile çok farkı olmadığını gördüm.
from sklearn.model_selection import cross_val_score
print(cross_val_score(lg_model,X,y,cv=5))

[0.6407332  0.64061682 0.64079139 0.64082868 0.64100326]


In [16]:
#Tahminleme yapılması örnek veri ile
yeni_veri=np.array([[0,0,1,0,0,0,1]])
lg_model.predict(yeni_veri)

array(['Katkıda bulunmuyor'], dtype=object)