header=None

In [81]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import SimpleImputer

In [82]:
dataset=pd.read_csv("heartTable.csv")


In [83]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [84]:
#dataset.isnull().sum()
#dataset.notnull().sum()
dataset.dtypes
dataset.columns

Index(['Yaş', 'Cinsiyet', 'cp', 'trtbps', 'chol', 'thalachh', 'fbs', 'restecg',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'Riskli'],
      dtype='object')

In [85]:
kat_dataset=dataset.select_dtypes(include=["object"]) #kategorik değişkenleri bulur
kat_dataset[15:25]

Cinsiyet
15      Kız
16      Kız
17      Kız
18    Erkek
19      Kız
20    Erkek
21    Erkek
22    Erkek
23    Erkek
24    Erkek

In [86]:
X_train.shape

(242, 13)

In [87]:
X_test.shape

(61, 13)

In [88]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [89]:
X[:,1]=le.fit_transform(X[:,1])
X[:,1]

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,

In [90]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [91]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [93]:
#X_test

In [95]:
#X_train

In [96]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [97]:
y_pred=regressor.predict(X_test)
np.set_printoptions(precision=3)

In [98]:
y_pred

array([ 0.068,  0.717,  0.737,  0.013,  0.236,  0.519,  0.183,  0.269,
       -0.188, -0.238,  0.652,  0.899,  0.108,  0.762,  0.994,  0.622,
        0.173,  0.651, -0.147,  0.757,  0.723,  0.452,  0.251,  0.241,
        0.801,  0.582,  0.319,  0.484,  1.06 ,  0.607,  0.621, -0.057,
        1.005,  0.659,  0.866,  0.575,  0.07 ,  0.776,  0.182,  0.316,
        0.668,  0.737,  0.426,  0.187,  0.52 ,  0.646,  0.75 ,  0.595,
        0.139,  0.737,  0.783,  0.568,  1.002,  0.772,  1.253,  0.247,
        0.934,  0.877,  0.692,  0.955,  0.718])

In [99]:
y_test

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1], dtype=int64)

In [106]:
#y_pred.reshape(len(y_pred),1)

In [102]:
#y_test.reshape(len(y_test),1)

In [103]:
sonuc=np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)    

In [110]:
sonuc[15:115]

array([[ 0.622,  1.   ],
       [ 0.173,  1.   ],
       [ 0.651,  1.   ],
       [-0.147,  0.   ],
       [ 0.757,  1.   ],
       [ 0.723,  1.   ],
       [ 0.452,  0.   ],
       [ 0.251,  0.   ],
       [ 0.241,  0.   ],
       [ 0.801,  1.   ],
       [ 0.582,  0.   ],
       [ 0.319,  0.   ],
       [ 0.484,  0.   ],
       [ 1.06 ,  1.   ],
       [ 0.607,  1.   ],
       [ 0.621,  0.   ],
       [-0.057,  0.   ],
       [ 1.005,  1.   ],
       [ 0.659,  1.   ],
       [ 0.866,  1.   ],
       [ 0.575,  0.   ],
       [ 0.07 ,  0.   ],
       [ 0.776,  1.   ],
       [ 0.182,  0.   ],
       [ 0.316,  0.   ],
       [ 0.668,  1.   ],
       [ 0.737,  1.   ],
       [ 0.426,  1.   ],
       [ 0.187,  0.   ],
       [ 0.52 ,  1.   ],
       [ 0.646,  1.   ],
       [ 0.75 ,  1.   ],
       [ 0.595,  0.   ],
       [ 0.139,  0.   ],
       [ 0.737,  1.   ],
       [ 0.783,  1.   ],
       [ 0.568,  1.   ],
       [ 1.002,  1.   ],
       [ 0.772,  1.   ],
       [ 1.253,  1.   ],
