randomfrorest rasgele karar ağaçlarından oluşur. rasgele k adet agaç oluşturuyordu. rasgele nokta secip bir ağac olusturuyor. Topluluk öğrenmesi.K adet agaç belirliyor. rasgele noktadan ağac oluşturuyor. yeni değer gelince agaclara soruyor. hepsinin ort alıyor.  cogunlugun dediği sonuc oluyoır.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("energy.csv")
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [4]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [5]:
y_pred=regressor.predict(X_test)
np.set_printoptions(precision=2)

In [6]:
y_pred

array([465.68, 431.41, 445.75, ..., 435.63, 429.81, 471.7 ])

In [7]:
y_test

array([463.9 , 431.07, 442.79, ..., 433.97, 433.39, 475.89])

In [8]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))  

[[465.68 463.9 ]
 [431.41 431.07]
 [445.75 442.79]
 ...
 [435.63 433.97]
 [429.81 433.39]
 [471.7  475.89]]


In [9]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.933190615722879

Liner Regresyonda 0.92 bulduk

Polinominal için bakalım

In [12]:
dataset=pd.read_csv("energy.csv")
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [12]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg=PolynomialFeatures(degree=5)
X_poly=poly_reg.fit_transform(X_train)
regressor=LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

In [13]:
y_pred=regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) 

[[454.18 457.05]
 [458.9  465.66]
 [435.95 440.7 ]
 ...
 [445.93 441.99]
 [447.93 455.68]
 [435.19 433.28]]


In [14]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9325901554570027

şimdi de SVR ye uygulayalım. Bunu yapmadan önce feature Scaler uygulamak lazım. Bunun içinde y yi çeviriyoruz.

In [15]:
dataset=pd.read_csv("energy.csv")
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [16]:
y=y.reshape(len(y),1)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [17]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
sc_y=StandardScaler()
X_train=sc_X.fit_transform(X_train)
y_train=sc_y.fit_transform(y_train)

In [18]:
from sklearn.svm import SVR
regressor=SVR(kernel="rbf")
regressor.fit(X_train,y_train.ravel())

SVR()

In [19]:
y_pred=sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) 

[[485.08 484.51]
 [467.02 467.74]
 [471.57 474.15]
 ...
 [434.   437.46]
 [431.37 434.78]
 [435.32 427.62]]


In [22]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.944478538967085

Random Forest ile çalışalım

In [20]:
from sklearn.model_selection import train_test_split
dataset=pd.read_csv("energy.csv")
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)


In [30]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=150)
regressor.fit(X_train,y_train)

RandomForestRegressor(n_estimators=150)

n_estimators=15 (kaç tane ağaç olacagı),  random_state=0 olunca rasgele dallanmıyor belli bitr noktadan başlıyor

In [31]:
y_pred=regressor.predict(X_test)
np.set_printoptions(precision=2)# virgülden sonra 2 adım
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))  

[[451.05 448.04]
 [466.67 468.14]
 [464.39 463.05]
 ...
 [488.82 488.57]
 [473.1  473.33]
 [439.17 435.02]]


In [33]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9627262767615634

Su model iyi veya kötü diyemeyiz. Doğrusal regresyon sadece doğrusal verilerde kullanılır. Doğrusal regresyonda amacımız regresyon çizgisinin tam üzerinde  üzerinde olmasıydı. Ama bu her zaman mümkün olmuyor. Çizgiden sapmalar oluyor. Bunun sakıncası ise doğru tahmini tam yapamıyor. Amacımız çizgiye olan uzaklığın en az olmasını sağlamak. Bunun için bazı algoritmalar var. SS değeri diye bir algoritma var.
polinominal için her boyutta çalışır. Doğrusal olmayan veriler için çok iyidir.
Ancak polinominalde degree(keskinlik) yi bizim seçmemiz bir eksikliktir. 
SVR ise doğrular olmayan verilerde kullanabiliriz. Ancak Scaler gerekiyor. Bir hesaplama ile sonuca ulaşıldığı için aykırı değer varsa feature bile işe yaramayabilir. Yorumlanması daha zor.
Desicion Tree : SVR ile karşılaştırırsak feature ye gerek yok. 
hem dogrusal hem dogrusal olmayanda çalışır. Ancak regresyon olarak belirli bi sonuc üretir. Net sonuc ta kötü bir algoritmadır.
Random Forest: Dogrusal dogrusal olmayanda , tek boyutlu çok boyutluda  cok iyi çalışır. Ancak Ağaç sayısını bizim vermemiz kötüdür. Yorumlamak zor. Rasgeleliğe çok bağlıdır. Agacı 5 yapmakla 10 yapmamkta elde edilen sonuç çok farklı çıkıyor.