## Breast Canser Sınıflandırması ##

In [64]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.metrics import plot_roc_curve

dataset=pd.read_csv("breast-cancer-wisconsin2.csv", header=None)
dataset.drop([0], axis=1,inplace=True)

In [65]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[ : , 5] = le.fit_transform(X[:, 5])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=0)


In [66]:
dataset.head()

1   2   3   4   5   6   7   8   9   10
0   5   1   1   1   2   1   3   1   1   2
1   5   4   4   5   7  10   3   2   1   2
2   3   1   1   1   2   2   3   1   1   2
3   6   8   8   1   3   4   3   7   1   2
4   4   1   1   3   2   1   3   1   1   2

In [67]:
dataset.eq('?').sum()

1      0
2      0
3      0
4      0
5      0
6     16
7      0
8      0
9      0
10     0
dtype: int64

In [68]:
dataset[6]=dataset[6].replace('?',np.NaN)

In [69]:
dataset.eq('?').sum()

1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
dtype: int64

In [70]:
dataset.dtypes

1      int64
2      int64
3      int64
4      int64
5      int64
6     object
7      int64
8      int64
9      int64
10     int64
dtype: object

In [71]:
dataset.notnull().sum()

1     699
2     699
3     699
4     699
5     699
6     683
7     699
8     699
9     699
10    699
dtype: int64

In [72]:
dataset.fillna(dataset.median(),inplace=True)

In [73]:
dataset.notnull().sum()

1     699
2     699
3     699
4     699
5     699
6     699
7     699
8     699
9     699
10    699
dtype: int64

In [74]:
#feature scaler
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train =sc.fit_transform(X_train)
X_test =sc.transform(X_test)

## Random Forest ##

In [92]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=1255, criterion='gini')
classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=1255)

In [93]:
y_pred=classifier.predict(X_test)

In [83]:
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))   

In [94]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[109   3]
 [  2  61]]


In [95]:
accuracy_score(y_test, y_pred)

0.9714285714285714

In [96]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           2       0.98      0.97      0.98       112
           4       0.95      0.97      0.96        63

    accuracy                           0.97       175
   macro avg       0.97      0.97      0.97       175
weighted avg       0.97      0.97      0.97       175



## Lojistik Regresyon ##

In [102]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='liblinear')  # bu satır değişiyor
classifier.fit(X_train, y_train)  #  bu satırda modelim eğitiliyor

LogisticRegression(solver='liblinear')

In [103]:
y_pred=classifier.predict(X_test)

In [104]:
y_pred

array([2, 2, 4, 2, 4, 2, 4, 2, 4, 4, 2, 2, 4, 4, 4, 2, 2, 4, 4, 2, 4, 4,
       2, 2, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2,
       4, 4, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4,
       4, 2, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2,
       4, 4, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2,
       4, 4, 4, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 4, 2, 2, 4, 4, 4, 4, 4, 2,
       2, 4, 4, 2, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4,
       2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2],
      dtype=int64)

In [105]:
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))   

In [106]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[108   4]
 [  5  58]]


In [107]:
accuracy_score(y_test, y_pred)

0.9485714285714286

In [108]:
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           2       0.96      0.96      0.96       112
           4       0.94      0.92      0.93        63

    accuracy                           0.95       175
   macro avg       0.95      0.94      0.94       175
weighted avg       0.95      0.95      0.95       175



## KNN ##

In [27]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=14, metric='minkowski', p=4)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=14, p=4)

In [29]:
y_pred=classifier.predict(X_test)

In [87]:
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) 

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[107   5]
 [  6  57]]


In [31]:
accuracy_score(y_test, y_pred)

0.9371428571428572

In [32]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           2       0.95      0.96      0.95       112
           4       0.92      0.90      0.91        63

    accuracy                           0.94       175
   macro avg       0.93      0.93      0.93       175
weighted avg       0.94      0.94      0.94       175



## Naive Bayes ##

In [33]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [34]:
y_pred=classifier.predict(X_test)
y_pred = classifier.fit(X_train, y_train).predict(X_test)

In [96]:
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))   

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[106   6]
 [  2  61]]


In [36]:
accuracy_score(y_test, y_pred)

0.9542857142857143

In [37]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           2       0.98      0.95      0.96       112
           4       0.91      0.97      0.94        63

    accuracy                           0.95       175
   macro avg       0.95      0.96      0.95       175
weighted avg       0.96      0.95      0.95       175



## SVC ##

In [38]:
from sklearn.svm import SVC
classifier = SVC(kernel= 'sigmoid', probability=True, degree=4, gamma='scale')#, degree=4, gamma='auto')  
#probability=true  predict_proba  nın çalışması için
classifier.fit(X_train, y_train)

SVC(degree=4, kernel='sigmoid', probability=True)

In [46]:
y_pred=classifier.predict(X_test)

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[106   6]
 [  5  58]]


In [48]:
accuracy_score(y_test, y_pred)

0.9371428571428572

In [49]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           2       0.95      0.95      0.95       112
           4       0.91      0.92      0.91        63

    accuracy                           0.94       175
   macro avg       0.93      0.93      0.93       175
weighted avg       0.94      0.94      0.94       175



In [51]:
#from sklearn.metrics import jaccard_score
#jaccard_score(y_test, y_pred)

## Decision Trees ##

In [20]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [21]:
y_pred=classifier.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[105   7]
 [  6  57]]


In [23]:
accuracy_score(y_test, y_pred)

0.9257142857142857

In [24]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           2       0.95      0.94      0.94       112
           4       0.89      0.90      0.90        63

    accuracy                           0.93       175
   macro avg       0.92      0.92      0.92       175
weighted avg       0.93      0.93      0.93       175

