# Sınıflandırma Algoritmalarının Diyabet Hastalığını Tahmin Sonuçları #

In [1]:
import numpy as np  #dizilerle çalışır
import matplotlib.pyplot as plt
import pandas as pd  # hariçten veri okur
from sklearn.impute import SimpleImputer

In [2]:
dataset=pd.read_csv("diabetes.csv")
dataset.drop(["HastaNo"], axis=1,inplace=True)
X=dataset.iloc[:,:].values

In [3]:
dataset.isnull().sum()

GebelikHaftasi                 3
Glikoz                         1
KanBasinci                     0
CiltKalinligi                  0
insulin                        0
BMI                            0
SoydaOlanHastalikFonksiyonu    3
Yas                            1
Hasta                          0
dtype: int64

In [4]:
dataset.notnull().sum()

GebelikHaftasi                 765
Glikoz                         767
KanBasinci                     768
CiltKalinligi                  768
insulin                        768
BMI                            768
SoydaOlanHastalikFonksiyonu    765
Yas                            767
Hasta                          768
dtype: int64

In [5]:
dataset[dataset.isnull().any(axis=1)]

GebelikHaftasi  Glikoz  KanBasinci  CiltKalinligi  insulin   BMI  \
5               NaN   116.0          74              0        0  25.6   
48              7.0   103.0          66             32        0  39.1   
133             8.0     NaN          74             31        0  38.3   
766             NaN   126.0          60              0        0  30.1   
767             NaN    93.0          70             31        0  30.4   

     SoydaOlanHastalikFonksiyonu   Yas  Hasta  
5                          0.201  30.0      0  
48                           NaN  31.0      1  
133                        0.457   NaN      0  
766                          NaN  47.0      1  
767                          NaN  23.0      0

In [6]:
dataset.dtypes #kategorik olmadıgı için

GebelikHaftasi                 float64
Glikoz                         float64
KanBasinci                       int64
CiltKalinligi                    int64
insulin                          int64
BMI                            float64
SoydaOlanHastalikFonksiyonu    float64
Yas                            float64
Hasta                            int64
dtype: object

In [7]:
imputer=SimpleImputer(missing_values=np.nan, strategy="mean")

In [8]:
imputer.fit(X[:,:-1])

SimpleImputer()

In [9]:
X[:,:-1]=imputer.transform(X[:,:-1])

In [10]:
X[:,:-1]

array([[  6.        , 148.        ,  72.        , ...,  33.6       ,
          0.627     ,  50.        ],
       [  1.        ,  85.        ,  66.        , ...,  26.6       ,
          0.351     ,  31.        ],
       [  8.        , 183.        ,  64.        , ...,  23.3       ,
          0.672     ,  32.        ],
       ...,
       [  5.        , 121.        ,  72.        , ...,  26.2       ,
          0.245     ,  30.        ],
       [  3.85098039, 126.        ,  60.        , ...,  30.1       ,
          0.47240915,  47.        ],
       [  3.85098039,  93.        ,  70.        , ...,  30.4       ,
          0.47240915,  23.        ]])

In [11]:
dataset.head()

GebelikHaftasi  Glikoz  KanBasinci  CiltKalinligi  insulin   BMI  \
0             6.0   148.0          72             35        0  33.6   
1             1.0    85.0          66             29        0  26.6   
2             8.0   183.0          64              0        0  23.3   
3             1.0    89.0          66             23       94  28.1   
4             0.0   137.0          40             35      168  43.1   

   SoydaOlanHastalikFonksiyonu   Yas  Hasta  
0                        0.627  50.0      1  
1                        0.351  31.0      0  
2                        0.672  32.0      1  
3                        0.167  21.0      0  
4                        2.288  33.0      1

In [12]:
dataset.eq(0).sum()

GebelikHaftasi                 111
Glikoz                           5
KanBasinci                      35
CiltKalinligi                  227
insulin                        374
BMI                             11
SoydaOlanHastalikFonksiyonu      0
Yas                              0
Hasta                          500
dtype: int64

In [13]:
dataset.shape

(768, 9)

In [14]:
dataset[['Glikoz','KanBasinci','CiltKalinligi','insulin','BMI','SoydaOlanHastalikFonksiyonu','Yas']]=dataset[['Glikoz','KanBasinci','CiltKalinligi','insulin','BMI','SoydaOlanHastalikFonksiyonu','Yas']].replace(0,np.NaN)

In [15]:
dataset.fillna(dataset.mean(),inplace=True)

In [16]:
dataset.head()

GebelikHaftasi  Glikoz  KanBasinci  CiltKalinligi     insulin   BMI  \
0             6.0   148.0        72.0       35.00000  155.548223  33.6   
1             1.0    85.0        66.0       29.00000  155.548223  26.6   
2             8.0   183.0        64.0       29.15342  155.548223  23.3   
3             1.0    89.0        66.0       23.00000   94.000000  28.1   
4             0.0   137.0        40.0       35.00000  168.000000  43.1   

   SoydaOlanHastalikFonksiyonu   Yas  Hasta  
0                        0.627  50.0      1  
1                        0.351  31.0      0  
2                        0.672  32.0      1  
3                        0.167  21.0      0  
4                        2.288  33.0      1

In [17]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [19]:
#feature scaler
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train =sc.fit_transform(X_train)
X_test =sc.transform(X_test)
X_train

array([[ 0.90728702,  0.93541443,  0.44607305, ...,  0.36780137,
         0.67621313,  1.70062029],
       [ 0.03433382, -0.8195407 , -1.05366073, ..., -0.63382702,
        -0.07189015, -0.96506855],
       [-1.12960378,  1.43209984,  1.44589558, ...,  2.81463643,
        -0.11996104, -0.88176577],
       ...,
       [ 0.03433382, -0.91887778, -0.63706802, ..., -1.13464121,
        -0.95819725, -1.04837132],
       [ 2.07122462, -1.21688903,  0.11279888, ..., -0.36195646,
        -0.50152376,  0.11786754],
       [ 0.32531822,  0.47184138,  0.77934723, ..., -0.02462752,
         0.51998273,  2.95016193]])

## KNN ##

In [20]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors =5, metric='minkowski', p=2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [21]:
y_pred=classifier.predict(X_test)

In [22]:
y_pred

array([1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [15]:
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))   

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[88 19]
 [17 30]]


In [24]:
accuracy_score(y_test, y_pred)

0.7662337662337663

In [25]:
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       107
           1       0.61      0.64      0.62        47

    accuracy                           0.77       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.77      0.77      0.77       154



In [26]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, y_pred)

0.45454545454545453

## Lojistik Regresyon ##

In [27]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='liblinear')  # bu satır değişiyor
classifier.fit(X_train, y_train)  #  bu satırda modelim eğitiliyor

LogisticRegression(solver='liblinear')

In [28]:
y_pred=classifier.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[97 10]
 [19 28]]


In [30]:
accuracy_score(y_test, y_pred)

0.8116883116883117

In [31]:
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.84      0.91      0.87       107
           1       0.74      0.60      0.66        47

    accuracy                           0.81       154
   macro avg       0.79      0.75      0.76       154
weighted avg       0.81      0.81      0.81       154



In [32]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, y_pred)

0.49122807017543857

## Random Forest ##

In [60]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 350, criterion = 'entropy')
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [61]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[94 13]
 [15 32]]


In [62]:
accuracy_score(y_test, y_pred)

0.8181818181818182

In [63]:
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.86      0.88      0.87       107
           1       0.71      0.68      0.70        47

    accuracy                           0.82       154
   macro avg       0.79      0.78      0.78       154
weighted avg       0.82      0.82      0.82       154



In [37]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, y_pred)

0.5166666666666667

## SVC ##

In [38]:
from sklearn.svm import SVC
classifier = SVC(kernel= 'sigmoid', probability=True, degree=4, gamma='scale')#, degree=4, gamma='auto')  
#probability=true  predict_proba  nın çalışması için
classifier.fit(X_train, y_train)

SVC(degree=4, kernel='sigmoid', probability=True)

In [39]:
y_pred=classifier.predict(X_test)

In [40]:
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))   

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[87 20]
 [19 28]]


In [42]:
accuracy_score(y_test, y_pred)

0.7467532467532467

In [43]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.82      0.81      0.82       107
           1       0.58      0.60      0.59        47

    accuracy                           0.75       154
   macro avg       0.70      0.70      0.70       154
weighted avg       0.75      0.75      0.75       154



In [44]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, y_pred)

0.417910447761194

## Naive Bayes ##

In [45]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [46]:
y_pred=classifier.predict(X_test)
y_pred = classifier.fit(X_train, y_train).predict(X_test)

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[92 15]
 [18 29]]


In [48]:
accuracy_score(y_test, y_pred)

0.7857142857142857

In [49]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.84      0.86      0.85       107
           1       0.66      0.62      0.64        47

    accuracy                           0.79       154
   macro avg       0.75      0.74      0.74       154
weighted avg       0.78      0.79      0.78       154



In [50]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, y_pred)

0.46774193548387094

## Decision Trees ##

In [51]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [52]:
y_pred=classifier.predict(X_test)

In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[83 24]
 [22 25]]


In [54]:
accuracy_score(y_test, y_pred)

0.7012987012987013

In [55]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.79      0.78      0.78       107
           1       0.51      0.53      0.52        47

    accuracy                           0.70       154
   macro avg       0.65      0.65      0.65       154
weighted avg       0.70      0.70      0.70       154



In [56]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, y_pred)

0.352112676056338