# Sınıflandırma Algoritmalarının Diyabet Hastalığını Tahmin Sonuçları #

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report,jaccard_score
from sklearn.naive_bayes import GaussianNB

dataset = pd.read_csv('heartTable.csv')
X = dataset.iloc[ :, : -1 ].values
y = dataset.iloc[ :, -1 ].values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[ : , 1] = le.fit_transform(X[:, 1])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state =8)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [3]:
dataset.isnull().sum()

Yaş         0
Cinsiyet    0
cp          0
trtbps      0
chol        0
thalachh    0
fbs         0
restecg     0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
Riskli      0
dtype: int64

In [4]:
dataset.notnull().sum()

Yaş         303
Cinsiyet    303
cp          303
trtbps      303
chol        303
thalachh    303
fbs         303
restecg     303
exng        303
oldpeak     303
slp         303
caa         303
thall       303
Riskli      303
dtype: int64

In [5]:
dataset[dataset.isnull().any(axis=1)]

Empty DataFrame
Columns: [Yaş, Cinsiyet, cp, trtbps, chol, thalachh, fbs, restecg, exng, oldpeak, slp, caa, thall, Riskli]
Index: []

In [6]:
dataset.dtypes #kategorik olmadıgı için

Yaş           int64
Cinsiyet     object
cp            int64
trtbps        int64
chol          int64
thalachh      int64
fbs           int64
restecg       int64
exng          int64
oldpeak     float64
slp           int64
caa           int64
thall         int64
Riskli        int64
dtype: object

In [7]:
dataset.head()

Yaş Cinsiyet  cp  trtbps  chol  thalachh  fbs  restecg  exng  oldpeak  slp  \
0   63    Erkek   3     145   233       150    1        0     0      2.3    0   
1   37    Erkek   2     130   250       187    0        1     0      3.5    0   
2   41      Kız   1     130   204       172    0        0     0      1.4    2   
3   56    Erkek   1     120   236       178    0        1     0      0.8    2   
4   57      Kız   0     120   354       163    0        1     1      0.6    2   

   caa  thall  Riskli  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [9]:
dataset.shape

(303, 14)

In [10]:
dataset.head()

Yaş Cinsiyet  cp  trtbps  chol  thalachh  fbs  restecg  exng  oldpeak  slp  \
0   63    Erkek   3     145   233       150    1        0     0      2.3    0   
1   37    Erkek   2     130   250       187    0        1     0      3.5    0   
2   41      Kız   1     130   204       172    0        0     0      1.4    2   
3   56    Erkek   1     120   236       178    0        1     0      0.8    2   
4   57      Kız   0     120   354       163    0        1     1      0.6    2   

   caa  thall  Riskli  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

## KNN ##

In [11]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors =5, metric='minkowski', p=2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [12]:
y_pred=classifier.predict(X_test)

In [13]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [15]:
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))   

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[20  2]
 [ 6 33]]


In [15]:
accuracy_score(y_test, y_pred)

0.8688524590163934

In [16]:
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.77      0.91      0.83        22
           1       0.94      0.85      0.89        39

    accuracy                           0.87        61
   macro avg       0.86      0.88      0.86        61
weighted avg       0.88      0.87      0.87        61



In [17]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, y_pred)

0.8048780487804879

## Lojistik Regresyon ##

In [18]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='liblinear')  # bu satır değişiyor
classifier.fit(X_train, y_train)  #  bu satırda modelim eğitiliyor

LogisticRegression(solver='liblinear')

In [19]:
y_pred=classifier.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[20  2]
 [ 7 32]]


In [21]:
accuracy_score(y_test, y_pred)

0.8524590163934426

In [22]:
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.74      0.91      0.82        22
           1       0.94      0.82      0.88        39

    accuracy                           0.85        61
   macro avg       0.84      0.86      0.85        61
weighted avg       0.87      0.85      0.85        61



In [23]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, y_pred)

0.7804878048780488

## Random Forest ##

In [24]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 350, criterion = 'entropy')
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[18  4]
 [ 7 32]]


In [26]:
accuracy_score(y_test, y_pred)

0.819672131147541

In [27]:
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.72      0.82      0.77        22
           1       0.89      0.82      0.85        39

    accuracy                           0.82        61
   macro avg       0.80      0.82      0.81        61
weighted avg       0.83      0.82      0.82        61



In [28]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, y_pred)

0.7441860465116279

## SVC ##

In [29]:
from sklearn.svm import SVC
classifier = SVC(kernel= 'sigmoid', probability=True, degree=4, gamma='scale')#, degree=4, gamma='auto')  
#probability=true  predict_proba  nın çalışması için
classifier.fit(X_train, y_train)

SVC(degree=4, kernel='sigmoid', probability=True)

In [30]:
y_pred=classifier.predict(X_test)

In [146]:
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))   

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[18  4]
 [ 6 33]]


In [32]:
accuracy_score(y_test, y_pred)

0.8360655737704918

In [33]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.75      0.82      0.78        22
           1       0.89      0.85      0.87        39

    accuracy                           0.84        61
   macro avg       0.82      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61



In [34]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, y_pred)

0.7674418604651163

## Naive Bayes ##

In [35]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [36]:
y_pred=classifier.predict(X_test)
y_pred = classifier.fit(X_train, y_train).predict(X_test)

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[21  1]
 [ 8 31]]


In [38]:
accuracy_score(y_test, y_pred)

0.8524590163934426

In [39]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.72      0.95      0.82        22
           1       0.97      0.79      0.87        39

    accuracy                           0.85        61
   macro avg       0.85      0.87      0.85        61
weighted avg       0.88      0.85      0.86        61



In [40]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, y_pred)

0.775

## Decision Trees ##

In [41]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [42]:
y_pred=classifier.predict(X_test)

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[17  5]
 [ 7 32]]


In [44]:
accuracy_score(y_test, y_pred)

0.8032786885245902

In [45]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.71      0.77      0.74        22
           1       0.86      0.82      0.84        39

    accuracy                           0.80        61
   macro avg       0.79      0.80      0.79        61
weighted avg       0.81      0.80      0.80        61



In [46]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, y_pred)

0.7272727272727273